### ISSUE TITLE
Design doc review # 3 - backend and frontend

### ISSUE THREAD

**Issue by aracpyon** [nickdraper8/RubyReel#3]
Hey Nick! Great job, here are my comments:

**Backend**
- [x] Do you need `index` routes for `users`? Or are you thinking of using this to get the number of subscribers? 
- [x] You might need to have two `index` routes for `Vidoes` one for `Video.all` and another for video index nested to `user` so you can grab all the videos that belongs to each youtuber. 

**Frontend**
Looks great so far!

**Comment by nickdraper8** [comment]
Hi Ara,

I understand what you are saying, and I have made the changes. You are right, I guess I wont need a users index anywhere, I'll be counting subscriptions using the subscriptions table and using that association. 

I also created another route for videos nested under user to get all that users videos.

Let me know if there is anything else you think I should add/change, thanks!

Best,
Nick
